### ISSUE TITLE
write an helper to transform ${linkid} to fhirpath in Expression

### ISSUE THREAD

**Issue by delcroip** [SwissTPH/pyfhirsdc#10]
${linkid} will need to be translated to 

%resource.repeat(item).where(linkId='4.2.1').answer.value

e.g. so to check a code one will have to write ${linkid}.code

**Comment by delcroip** [comment]
see reason here https://github.com/google/android-fhir/issues/819

**Comment by magp18** [comment]
@delcroip and in your example, if you write ${linkdid}.code in the excel file you should get %resource.repeat(item).where(linkId='linkid').answer.code in the JSON ?
