### ISSUE TITLE
create profiles

### ISSUE THREAD

**Issue by delcroip** [SwissTPH/pyfhirsdc#5]
The questionnaires must create the custom profiles 
http://www.hl7.org/fhir/structuredefinition.html

**Comment by magp18** [comment]
Still to do :
- [x] Create general function for mapping of the resource types 
- [x] Group all the sheets together and only then work on profiles (right now working on it per sheet)
- [x] Allow for references to other profiles

**Comment by magp18** [comment]
References are allowed but only one reference to a target profile. If references to multiple profiles should be supported, how to represent it in the input file should be discussed
